---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcsproxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gcsproxy
    spec:
      containers:
        - name: gcsproxy
          image: gcr.io/ea-seed-gcp/gcsproxy:latest
          command:
            - /gcsproxy
            - -b
            - 0.0.0.0:8080
            - -v
          ports:
            - name: web
              containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 50Mi
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: gcsproxy
  labels:
    app: gcsproxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: web
  selector:
    app: gcsproxy

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-static-web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /my-static-web-bucket/prefix
    nginx.ingress.kubernetes.io/auth-signin: https://oauth-proxy.example.com/oauth2/start
    nginx.ingress.kubernetes.io/auth-url: https://oauth-proxy.example.com/oauth2/auth
spec:
  tls:
    - hosts:
        - my-site.example.com
      secretName: wildcard-example-com-tls
  rules:
    - host: "my-site.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: gcsproxy
              servicePort: 8080
